Loading python/3.11.6--gcc--8.5.0
  Loading requirement: bzip2/1.0.8-gp5wcz5 libmd/1.0.4-wja3f5q
    libbsd/0.11.7-cgxjopl expat/2.5.0-bptl3xw ncurses/6.4-asx3jea
    readline/8.2-nyw6mp6 gdbm/1.23-fs6otck libiconv/1.17-d7yvx2s
    xz/5.4.1-hubmwr5 zlib-ng/2.1.4-6htiapk libxml2/2.10.3-5eeeokp
    pigz/2.7-bopr5vp zstd/1.5.5-gawytfl tar/1.34-amqus5s gettext/0.22.3-2g7elif
    libffi/3.4.4-6r7brdq libxcrypt/4.4.35-ss2rzin sqlite/3.43.2
    util-linux-uuid/2.38.1-jkdi7kv
Running on  nodes
---------------------------------------------
SLURM job ID:        13754089
SLURM job node list: lrdn1681
DATE:                Tue Mar 11 10:00:55 CET 2025
---------------------------------------------
Traceback (most recent call last):
  File "/leonardo/home/userexternal/scanduss/transformers/src/transformers/models/stldec/validate_run_e_6_10_2.py", line 37, in <module>
    AutoModelForCausalLM.register(STLConfig, STLForCausalLM)
  File "/leonardo/home/userexternal/scanduss/transformers/src/transformers/models/auto/auto_factory.py", line 584, in register
    raise ValueError(
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'configuration.STLConfig'> and you passed <class 'configuration2.STLConfig'>. Fix one of those so they match!
srun: error: lrdn1681: task 0: Exited with exit code 1
DONE!
